# This is the docker-compose file to run Medplum's required background serivces
# It can be used to quickly run 2 services:
#   1) The Postgres database
#   2) The Redis cache
# You can start all services by running "docker-compose up"
version: '3.7'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=medplum
      - POSTGRES_PASSWORD=medplum
    volumes:
      - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - ./postgres/:/docker-entrypoint-initdb.d/
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf -p 5433
    ports:
      - '5433:5433'
  redis:
    image: redis:6
    restart: always
    command: redis-server --requirepass medplum --port 6380
    ports:
      - '6380:6380'
